# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: biologiste-db
    environment:
      POSTGRES_DB: biologiste_db
      POSTGRES_USER: biologiste_user
      POSTGRES_PASSWORD: biologiste_pass
    ports:
      - "5433:5432"  # Port externe : interne
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: