apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-config-service
  labels:
    app: farm-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm-config-service
  template:
    metadata:
      labels:
        app: farm-config-service
    spec:
      containers:
        - name: farm-config-service
          # ✅ Nom de l'image générée par Docker Compose
          image: ferme-agricole-app-farm-config-service:latest

          # ✅ IMPORTANT pour le local : Utilise l'image de votre PC, ne télécharge pas
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 9999

          env:
            # ✅ On pointe vers le service Kubernetes 'farm-discovery-service'
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://farm-discovery-service:8761/eureka/"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 10 # Un peu plus long pour Java (Spring Boot)
            periodSeconds: 10
            failureThreshold: 4

---
apiVersion: v1
kind: Service
metadata:
  name: farm-config-service
spec:
  # ✅ ClusterIP suffit pour que les autres microservices lui parlent.
  # Pas besoin d'exposer le Config Service au public.
  type: ClusterIP
  selector:
    app: farm-config-service
  ports:
    - port: 9999
      targetPort: 9999